name: Covid19
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - numpy
  - scipy
  - pandas
  - matplotlib
  - ipywidgets
  - jupyter_contrib_nbextensions
  - rise
  - plotly=3.10.0
